# Generated by Django 4.2 on 2024-01-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(choices=[('17-20', '17-20'), ('21-24', '21-24'), ('25-30', '25-30'), ('30 Dan Yuqori', '30 Dan Yuqori')], max_length=45)),
                ('experience', models.CharField(choices=[('1-3 Oy', '1-3 Oy'), ('3-6 Oy', '3-6 Oy'), ('1-3 Yil', '1-3 Yil'), ('3-5 Yil', '3-5 Yil'), ('5 Yildan Yuqori', '5 Yildan Yuqori')], max_length=45)),
                ('job', models.CharField(choices=[('Ofitsant', 'Ofitsant'), ('Milliy Taomlar Oshpazi', 'Milliy Taomlar Oshpazi'), ('Uygçur Taomlar Oshpazi', 'Uygçur Taomlar Oshpazi'), ('Shashlikpaz', 'Shashlikpaz'), ('Idish yuvuchi', 'Idish yuvuchi')], max_length=45)),
                ('phone', models.CharField(max_length=15)),
                ('text', models.TextField()),
            ],
        ),
    ]
